# -*- coding: utf-8 -*-
#!/usr/bin/env python3
#Module de communication FFTESC
from .data import (
    FtescRealtimeData,
    FtescFault,
    FtescDualData,
    FtescFirmwareInfo,
    MotorType,
    SensorlessMode,
    FOCMode,
    HallConfig,
    FOCConfig,
    RampConfig,
    BrakeConfig,
    InputControlConfig,
    ControlType,
    ControlCommand,
    LimitsConfig,
    SpeedPIDConfig,
    DualSetupConfig,
    DualMode,
    BatteryConfig,
    BatteryType,
    IMUConfig,
    IMUType,
    CANConfig,
    CANMode,
    CANBaudrate,
    MotorConfig,
    DualMotorConfig,
    PeripheralConfig,
    DEFAULT_MOTOR_CONFIG,
    DEFAULT_DUAL_CONFIG,
)
from .protocol import (
    UartCommand,
    crc16_ftesc,
    build_frame,
    parse_frame,
    parse_realtime_data,
    parse_firmware_info,
    build_obtain_all_ids_frame,
    decompose_u8,
    compose_u8,
)
from .transport import FtescTransport, ConnectionState, SerialConfig
from .config_protocol import (
    CTRL_MOTOR_A, CTRL_MOTOR_B, CTRL_GLOBAL,
    SEC_MOTOR, SEC_HALL, SEC_FOC, SEC_LIMITS,
    SEC_RAMP, SEC_BRAKE, SEC_INPUT_CTRL, SEC_SPEED_PID,
    SEC_BATTERY, SEC_DUAL, SEC_IMU, SEC_CAN, SEC_PERIPHERALS,
    build_read_config_frame, build_write_config_frame,
    parse_config_response, decode_section_response,
    encode_section, decode_section,
    SECTION_FIELDS,
)

from .resources import get_resource_path

__all__ = [
    'FtescRealtimeData',
    'FtescFault',
    'FtescDualData',
    'FtescFirmwareInfo',
    'MotorType',
    'SensorlessMode',
    'FOCMode',
    'HallConfig',
    'FOCConfig',
    'RampConfig',
    'BrakeConfig',
    'InputControlConfig',
    'ControlType',
    'ControlCommand',
    'LimitsConfig',
    'SpeedPIDConfig',
    'DualSetupConfig',
    'DualMode',
    'BatteryConfig',
    'BatteryType',
    'IMUConfig',
    'IMUType',
    'CANConfig',
    'CANMode',
    'CANBaudrate',
    'PeripheralConfig',
    'MotorConfig',
    'DualMotorConfig',
    'DEFAULT_MOTOR_CONFIG',
    'DEFAULT_DUAL_CONFIG',
    'UartCommand',
    'crc16_ftesc',
    'build_frame',
    'parse_frame',
    'parse_realtime_data',
    'parse_firmware_info',
    'build_obtain_all_ids_frame',
    'FtescTransport',
    'ConnectionState',
    'SerialConfig',
    'decompose_u8',
    'compose_u8',
    'CTRL_MOTOR_A', 'CTRL_MOTOR_B', 'CTRL_GLOBAL',
    'SEC_MOTOR', 'SEC_HALL', 'SEC_FOC', 'SEC_LIMITS',
    'SEC_RAMP', 'SEC_BRAKE', 'SEC_INPUT_CTRL', 'SEC_SPEED_PID',
    'SEC_BATTERY', 'SEC_DUAL', 'SEC_IMU', 'SEC_CAN', 'SEC_PERIPHERALS',
    'build_read_config_frame', 'build_write_config_frame',
    'parse_config_response', 'decode_section_response',
    'encode_section', 'decode_section',
    'SECTION_FIELDS',
    'get_resource_path',
]

__version__ = '1.01'
